[tool.poetry]
name = "ragas"
version = "0.1.0"
description = ""
authors = ["AbdulSametTurkmenoglu <116945109+Samet80@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
